# -*- coding: utf-8 -*-
"""Task04_CS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16WwedAXLkB9eXUaSliwtVXPxVQOXrSVh
"""

import datetime

LOG_FILE = "keystrokes_log.txt"

def log_input(user_input):
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    with open(LOG_FILE, "a") as file:
        file.write(f"[{timestamp}] {user_input}\n")


def main():
    print("===== Ethical Keystroke Logger =====")
    print("This program logs only what you type here.")
    print("Type 'exit' to stop.\n")

    while True:
        user_input = input("Enter text: ")

        if user_input.lower() == "exit":
            print("Logging stopped. Data saved to keystrokes_log.txt")
            break

        log_input(user_input)
        print("Logged successfully.\n")


if __name__ == "__main__":
    main()